// dict.js — translation dictionary for the Lingua marketing site.
// Loaded BEFORE i18n.js so that window.I18N_DICT is in place when first lookup runs.
window.I18N_DICT = {
  en: {
    // Nav
    'nav.menu.company':   'Company',
    'nav.menu.product':   'Product',
    'nav.menu.resources': 'Resources',
    'nav.about':          'About us',
    'nav.careers':        'Careers',
    'nav.affiliates':     'Affiliates',
    'nav.whatsnew':       "What's new",
    'nav.usecases':       'Use cases',
    'nav.pricing':        'Pricing',
    'nav.business':       'For business',
    'nav.support':        'Support',
    'nav.sales':          'Sales',
    'nav.typingtest':     'Typing test',
    'nav.login':          'Log in',
    'nav.contact':        'Contact',
    'nav.cta':            'Download',

    // Hero
    'hero.eyebrow':       'Voice-first — who likes typing anyways?',
    'hero.title.start':   "don't ",
    'hero.title.typo':    'leyrb',
    'hero.title.target':  'keyboard',
    'hero.title.tail.more': '',
    'hero.title.tail.em':   'type',
    'hero.title.tail.typo': 'tuoe',
    'hero.title.tail.dot':  '.',
    'hero.sub':           'Lingua is the new way to write — speak naturally and let your computer turn it into clean, formatted text in any app.',
    'hero.platform.mac':     'Mac',
    'hero.platform.windows': 'Windows',
    'hero.cta.test':      'Try the typing test',
    'hero.cta.try':       'Try Lingua',
    'hero.fine':          'Free to start. No credit card. Mac & Windows.',
    'hero.transcript.app': 'Transcribing into Notes',
    'hero.t.0':  "Lingua helps me find my flow without my typing holding me back.",
    'hero.t.1':  "Writing on my computer has finally become effortless.",
    'hero.t.2':  "When I research with AI, Lingua saves me hours of giving it context.",
    'hero.t.3':  "With the time I've saved not typing slowly, the whole year paid for itself in a week.",
    'hero.t.4':  "Answering client emails went from a nightmare to feeling like a normal conversation.",
    'hero.t.5':  "Finishing my medical reports faster with Lingua means I get to have dinner with my family.",
    'hero.t.6':  "Sending personalised notes to my students — Lingua lets me do that in minutes instead of hours.",
    'hero.t.7':  "It's doubled my productivity. 2x, easily.",
    'hero.t.8':  "When my brain is fried and I need to write in English, I speak Spanish and let Lingua translate.",
    'hero.t.9':  "My most important tool after the camera.",
    'hero.t.10': "Meeting minutes in 5 minutes instead of 30.",
    'hero.t.11': "3 → 4 articles a week without burning out.",
    'hero.t.12': "Keeping a log of every action for my engineering team has never been this easy.",
    'hero.t.13': "Lingua lets me stop wasting time typing and spend more time doing what I love — creating.",
    'hero.t.14': "Tripled my weekly output.",
    'hero.t.15': "This has saved my life. Typing wrecks your fingers.",
    'hero.t.16': "The best gift you can give your mental health.",
    'hero.t.17': "The invisible engine behind my productivity.",
    'hero.t.18': "10 hours a week, back in my pocket.",
    'hero.t.19': "The best thing that's happened to the screenwriting industry.",

    // CTA band
    'cta.title.a':  'Start ',
    'cta.title.em': 'speaking',
    'cta.title.b':  '.',
    'cta.body':     'Lingua works in any app you already use. Free to start.',
    'cta.try':      'Try Lingua',
    'cta.download': 'Download',
    'cta.fine':     'Mac & Windows · 60+ languages',

    // Apps section
    'apps.title.a':  'Write faster in ',
    'apps.title.em': 'all',
    'apps.title.b':  ' your apps.',
    'apps.sub':      'Lingua works system-wide. Speak in any app, any window — your words land where the cursor is.',
    'apps.any.eb':   'Any app',
    'apps.any.sub':  'Wherever the cursor blinks',

    // Tone block
    'tone.eyebrow':       'App-aware',
    'tone.title.a':       'It already knows ',
    'tone.title.em':      'where',
    'tone.title.b':       ' you\'re writing.',
    'tone.body':          'Same words spoken — Lingua reads the app and adjusts tone, length, and formatting so the message lands right.',
    'tone.said.label':    'You said: ',
    'tone.said.text':     '"tell the team the launch is moving to friday"',
    'tone.row.slack':     'team — moving launch to fri 🤝',
    'tone.row.gmail':     'Quick heads-up: launch is now Friday. Updated brief attached.',
    'tone.row.linkedin':  'Heads up — launch shifts to Friday for a stronger reveal.',
    'tone.row.whatsapp':  'launch → friday 👍',
    'tone.pill.casual':       'casual',
    'tone.pill.formal':       'formal',
    'tone.pill.professional': 'professional',
    'tone.pill.brief':        'brief',

    // Personas
    'personas.eyebrow':         'Made for you',
    'personas.title.a':         'Lingua is made ',
    'personas.title.em':        'for you',
    'personas.title.b':         '.',
    'personas.heading.a':       'Built for ',
    'personas.cta.learn':       'Learn more',
    'personas.cta.download':    'Download',
    'personas.consultants.tab': 'Consultants',
    'personas.consultants.em':  'consultants',
    'personas.consultants.body':'Decks, memos, and client emails — drafted in the time it takes to walk to coffee.',
    'personas.creators.tab':    'Creators',
    'personas.creators.em':     'creators',
    'personas.creators.body':   'Capture rough ideas at the speed you have them. Lingua keeps up with the firehose.',
    'personas.devs.tab':        'Developers',
    'personas.devs.em':         'developers',
    'personas.devs.body':       'PRs, comments, and changelogs — narrated, not typed. Stays in your editor.',
    'personas.sales.tab':       'Sales',
    'personas.sales.em':        'sales teams',
    'personas.sales.body':      'Follow-ups while you walk between calls. Same tone, same speed, no backlog.',
    'personas.students.tab':    'Students',
    'personas.students.em':     'students',
    'personas.students.body':   'Lecture notes and essays without the wrist pain. Lingua writes while you think.',

    // Values
    'values.eyebrow':   'Why Lingua',
    'values.title':     'Voice should feel like the most natural way to use a computer.',
    'values.1.eb':      '01',
    'values.1.t':       'Built for ',
    'values.1.em':      'every app',
    'values.1.body':    'Lingua works wherever you write — no plugins, no integrations, no friction.',
    'values.2.eb':      '02',
    'values.2.t':       'A real ',
    'values.2.em':      'craft',
    'values.2.body':    'Punctuation, casing, paragraphs. The little things that make speech read like writing.',
    'values.3.eb':      '03',
    'values.3.t':       'Made for ',
    'values.3.em':      'humans',
    'values.3.body':    'Pauses, fillers, second thoughts — Lingua understands the way people actually talk.',
    'values.4.eb':      '04',
    'values.4.t':       'Private by ',
    'values.4.em':      'default',
    'values.4.body':    'On-device when possible. Your voice never trains a model. You\'re always in control.',

    // Love letters
    'love.eyebrow':  'Loved by writers',
    'love.title.a':  'A few ',
    'love.title.em': 'love letters',
    'love.title.b':  '.',
    'love.who1':  'Tara',
    'love.role1': 'Designer',
    'love.q1':    'I stopped dreading email. Lingua just gets the tone right.',
    'love.who2':  'Rahul',
    'love.role2': 'PM',
    'love.q2':    'Twice the words, half the wrist. I write more because it costs less.',
    'love.who3':  'Suzanne',
    'love.role3': 'Author',
    'love.q3':    'It\'s the closest thing to thinking onto the page that I\'ve ever used.',

    // Footer
    'footer.col.company':   'Company',
    'footer.col.product':   'Product',
    'footer.col.resources': 'Resources',
    'footer.col.contact':   'Contact',
    'footer.twitter':       'X / Twitter',
    'footer.linkedin':      'LinkedIn',
    'footer.copy':          '© 2025 Lingua. Made by hand.',
    'footer.terms':         'Terms',
    'footer.privacy':       'Privacy',
    'footer.data':          'Data',





    // Typing test
    'tt.back':           '← Back to Lingua',
    'tt.eyebrow':        'The typing test',
    'tt.h.a':            'How fast do you ',
    'tt.h.em':           'actually',
    'tt.h.b':            ' type?',
    'tt.sub':            "Type the sentence below. The clock starts on your first correct keystroke. Mistakes don't count — you can't move past them.",
    'tt.phrase':         "I'd never really thought about it, but typing on a keyboard is so much slower than talking. What would my life look like if I never had to type again?",
    'tt.status.ready':   'READY · start typing to begin',
    'tt.status.recording': 'RECORDING',
    'tt.status.done':    'DONE',
    'tt.chars':          'chars',
    'tt.hint.done.a':    'Press ',
    'tt.hint.done.b':    ' to try again',
    'tt.hint.go':        'Just start typing — the clock starts on your first correct keystroke',
    'tt.scrollcue':      'Your results below',
    'tt.unit':           'words / min',
    'tt.scenario.slow':  "Lingua isn't a luxury — it's a return of your day.",
    'tt.scenario.mid':   'Even decent typists leave hours on the table every week.',
    'tt.scenario.fast':  'Impressive. Now imagine what happens when you stop typing at all.',
    'tt.lingua.cap.a':   'Lingua dictation — about ',
    'tt.lingua.cap.b':   '× faster.',
    'tt.saved.a':        'You took ',
    'tt.saved.took':     ' seconds',
    'tt.saved.b':        ' to type this. Speaking it: ',
    'tt.saved.spoken':   ' seconds',
    'tt.saved.c':        '. ',
    'tt.saved.bold.a':   'Lingua would have given you back ',
    'tt.saved.bold.b':   ' seconds — on this one sentence.',
    'tt.bar.you':        'You, just now',
    'tt.bar.avg':        'Average typist',
    'tt.bar.lingua':     'Lingua dictation',
    'tt.bar.unit':       'wpm',
    'tt.calc.h':         'Now multiply that',
    'tt.calc.lede.a':    'If you type ',
    'tt.calc.lede.em':   'about ',
    'tt.calc.lede.h':    'hour',
    'tt.calc.lede.hs':   'hours',
    'tt.calc.lede.b':    ' a day at your speed, here\'s what Lingua gives back every week:',
    'tt.calc.label':     'Hours typing per workday',
    'tt.calc.unit':      'hours / week saved',
    'tt.cta.dl':         'Download Lingua — free',
    'tt.cta.again':      'Try again',

    // Use cases page
    'uc.eyebrow':           'Use cases',
    'uc.hero.h.a':          'Built for the way ',
    'uc.hero.h.em':         'you',
    'uc.hero.h.b':          ' actually work.',
    'uc.hero.sub':          "Five jobs Lingua does every day, with the actual prompts and emails people send. No demos, no marketing fluff — the same copy you'd write, only faster.",
    'uc.jump.consultants':  'Consultants',
    'uc.jump.creators':     'Creators',
    'uc.jump.devs':         'Developers',
    'uc.jump.sales':        'Sales',
    'uc.jump.students':     'Students',
    'uc.worksIn':           'Works in',

    // Consultants
    'uc.cons.tag':          'For consultants',
    'uc.cons.h.a':          'Bill the hours. ',
    'uc.cons.h.em':         'Skip',
    'uc.cons.h.b':          ' the typing.',
    'uc.cons.sub':          'Decks, client memos, post-call recaps — the typing tax that eats your billable hours. Walk-and-talk your way through follow-ups, dictate frameworks straight into slides, and leave the office before sundown.',
    'uc.cons.e1.before':    'Right after a client call',
    'uc.cons.e1.b.a':       '"Recap the Lufthansa workshop — three deliverables, owners, dates. Send to ',
    'uc.cons.e1.b.em':      'olivia@',
    'uc.cons.e1.b.b':       ' and cc the partner."',
    'uc.cons.e2.before':    'In the airport lounge',
    'uc.cons.e2.b':         'Dictate a 2×2 framework for the next steerco — Lingua drops it straight into your slide notes, formatted.',
    'uc.cons.e3.before':    'End of week, Slack to staffing',
    'uc.cons.e3.s':         "need to flag I'm at 60% next wk only mon/tue, then offsite",
    'uc.cons.e3.em':        "Quick capacity note: I'm at 60% next week (Mon–Tue only), then offsite Wed–Fri.",
    'uc.cons.stat':         '2.4 hrs/day',
    'uc.cons.statLbl':      'average time saved by consultants in the Lingua beta',
    'uc.cons.demoTitle':    'Recap — Lufthansa workshop.docx',
    'uc.cons.live':         'Lingua is dictating · Spanish → English',
    'uc.cons.draft':        `Recap: Q3 brand workshop with Lufthansa\nOwner: A. Mendez · 12 Mar\n\nThree things we agreed to ship by next Monday:\n\n1. Tighten the positioning around "the network you fly home with." Olivia owns the deck rewrite.\n\n2. Cut the loyalty pillar from the 2026 plan — overlap with miles team.`,

    // Creators
    'uc.cre.tag':           'For creators',
    'uc.cre.h.a':           'Reply to ',
    'uc.cre.h.em':          'everyone',
    'uc.cre.h.b':           '. Sound like you.',
    'uc.cre.sub':           'Ideas hit fast, but execution is slow. Breeze through unread DMs, comment replies, and draft posts with your voice. Create more, type less.',
    'uc.cre.e1.before':     'DMs piling up',
    'uc.cre.e1.b.a':        'Walk through breakfast — Lingua replies to ',
    'uc.cre.e1.b.em':       'thirty unread Instagram DMs',
    'uc.cre.e1.b.b':        ' in your tone, queues each one for one-tap send.',
    'uc.cre.e2.before':     'Drafting a video caption',
    'uc.cre.e2.b':          'Talk through the idea once. Get back a tight 2-line hook, three hashtags, and a 60-word longer caption — pick whichever fits.',
    'uc.cre.e3.before':     'Brand pitch in your inbox',
    'uc.cre.e3.s':          'thx but the price is too low',
    'uc.cre.e3.em':         "Thanks for the offer. The rate is below my usual band — happy to share a counter if you're flexible on usage rights.",
    'uc.cre.stat':          '5×',
    'uc.cre.statLbl':       'faster inbox-zero across IG, TikTok and email — measured during creator beta',
    'uc.cre.demoTitle':     'Inbox · 3 unread',
    'uc.cre.dm1.who':       'Maya R.',
    'uc.cre.dm1.msg':       'loved the latest video — can I share it on our newsletter?',
    'uc.cre.dm1.reply':     "Yes please — go for it. Send me the link when it's live so I can re-share.",
    'uc.cre.dm2.who':       'Felipe',
    'uc.cre.dm2.msg':       'yo are you still doing the lighting workshop in May?',
    'uc.cre.dm2.reply':     'Hey! Yes, May 18th, two slots left. Want me to hold one for you?',
    'uc.cre.dm3.who':       'Studio Ono',
    'uc.cre.dm3.msg':       "Quick favour: any chance you'd guest-host episode 12?",
    'uc.cre.dm3.reply':     "Tempting — depends on dates. Drop me the recording schedule and I'll check.",

    // Developers
    'uc.dev.tag':           'For developers',
    'uc.dev.h.a':           'Stay in ',
    'uc.dev.h.em':          'flow',
    'uc.dev.h.b':           '. Ship anyway.',
    'uc.dev.sub':           'Dictate in natural language and let Lingua translate — perfect for Cursor, VS Code, or wherever you build. From commit messages to refactors, stay in flow.',
    'uc.dev.e1.before':     'Inside Cursor',
    'uc.dev.e1.b.a':        '"Refactor this ',
    'uc.dev.e1.b.em1':      'useEffect',
    'uc.dev.e1.b.b':        ' into a custom hook called ',
    'uc.dev.e1.b.em2':      'useUsers',
    'uc.dev.e1.b.c':        ', return loading and error." → Lingua hands it to your AI as a clean prompt, no typos.',
    'uc.dev.e2.before':     'Commit time',
    'uc.dev.e2.b.a':        '"',
    'uc.dev.e2.b.em':       'fix: handle empty cart in checkout — skip totals call when items is 0',
    'uc.dev.e2.b.b':        '". One sentence, conventional-commits format, done.',
    'uc.dev.e3.before':     'PR review on a busy day',
    'uc.dev.e3.b':          'Talk through the diff out loud; Lingua drops a structured review with file:line callouts into the comment box.',
    'uc.dev.stat':          '120 wpm',
    'uc.dev.statLbl':       "dictating prompts beats typing them — and it's gentler on wrists",
    'uc.dev.demoTitle':     '~ / users.tsx — Cursor',
    'uc.dev.dictation':     'add a useEffect that fetches /api/users on mount and stashes the result in state, with a try-catch around it',

    // Sales
    'uc.sales.tag':         'For sales',
    'uc.sales.h.a':         "Follow up while it's ",
    'uc.sales.h.em':        'warm',
    'uc.sales.h.b':         '.',
    'uc.sales.sub':         'Slow follow-ups mean lost deals. Send instant follow-ups after meetings, personalize outreach, and punch up your pitch — without typing a word.',
    'uc.sales.e1.before':   'Walking out of the demo',
    'uc.sales.e1.b':        '"Send Priya the pricing one-pager, the integrations doc, and book a slot Thursday 2pm." Lingua queues all three before you reach the elevator.',
    'uc.sales.e2.before':   'Cold outreach, real voice',
    'uc.sales.e2.b.a':      'Talk one personalised opener; Lingua spins it into ',
    'uc.sales.e2.b.em':     '20 variants',
    'uc.sales.e2.b.b':      ' for your sequencer — same hook, different specifics per account.',
    'uc.sales.e3.before':   'Logging the call',
    'uc.sales.e3.s':        'cl wants pilot, push 6mo, stuck on procurement',
    'uc.sales.e3.em':       'Client agreed to a 6-month pilot pending procurement review. Next step: intro to security on Mon.',
    'uc.sales.stat':        '38%',
    'uc.sales.statLbl':     'higher reply rate when follow-ups go out within an hour of the call',
    'uc.sales.demoTitle':   'Lingua queue · sending now',
    'uc.sales.m1.who':      'Priya · Acme',
    'uc.sales.m1.sub':      'Following up on your demo — three numbers from your team',
    'uc.sales.m2.who':      'Jordan · Northwind',
    'uc.sales.m2.sub':      'Recap & next step: kicking off the pilot in week 2',
    'uc.sales.m3.who':      'Hira · Globex',
    'uc.sales.m3.sub':      'Loved the conversation — sending the pricing you asked for',
    'uc.sales.m4.who':      'Tom · Initech',
    'uc.sales.m4.sub':      'Quick answer to your churn question + a 1-pager',
    'uc.sales.counterLbl':  'follow-ups sent today · since 9:04 am',

    // Students
    'uc.stu.tag':           'For students',
    'uc.stu.h.a':           'From the ',
    'uc.stu.h.em':          'lecture',
    'uc.stu.h.b':           ' to the page.',
    'uc.stu.sub':           "Blank pages and looming deadlines? Lingua's got you. Capture lectures, draft cover letters, break through writer's block — all by talking.",
    'uc.stu.e1.before':     'In a 9am lecture',
    'uc.stu.e1.b.a':        'Whisper through the slide; Lingua leaves you a tidy bulleted note in ',
    'uc.stu.e1.b.em':       'Notion',
    'uc.stu.e1.b.b':        ', with the date and lecturer auto-tagged.',
    'uc.stu.e2.before':     'Cover letter, ten minutes before deadline',
    'uc.stu.e2.b':          'Talk through your story for two minutes; Lingua returns a 250-word draft, role-specific opener, and three "what to cut" suggestions.',
    'uc.stu.e3.before':     'Group project Slack',
    'uc.stu.e3.s':          'can someone do the slides i can do voiceover?',
    'uc.stu.e3.em':         'Could one of you take the slides? I can record the voiceover by Thursday — just need the script the day before.',
    'uc.stu.stat':          '3 hrs/week',
    'uc.stu.statLbl':       'average reading & writing time recovered by students in pilot programs',
    'uc.stu.demoTitle':     'Ethics 201 — Lecture 4 notes',
    'uc.stu.note1':         'Kant: imperatives — categorical vs. hypothetical',
    'uc.stu.note2':         "Categorical = unconditional, e.g. 'don't lie'",
    'uc.stu.note3':         "Hypothetical = means-end, e.g. 'study to pass'",
    'uc.stu.note4':         'Critique: too rigid? trolley problem, etc.',
    'uc.stu.note5':         'Test on Friday — focus on §2 of Groundwork',

    // What's new page
    'new.eyebrow':       "What's new · Spring 2026",
    'new.lede.a':        'Speak in ',
    'new.lede.em':       'any',
    'new.lede.b':        ' language. Sound like you mean it.',
    'new.intro':         'Two new things you can do with Lingua today. Same simple idea — talk normally, get clean writing back — now with a passport and a sense of context.',

    // Feature 1
    'new.f1.tag':        'New feature',
    'new.f1.h.a':        'Speak one language, ',
    'new.f1.h.em':       'write',
    'new.f1.h.b':        ' another.',
    'new.f1.b':          'Dictate in the language you think in. Lingua writes in the language you need — instantly, in any app, with the nuance of a real translator instead of a literal one.',
    'new.f1.youSaid':    'You said',
    'new.f1.wrote.en':   '→ Lingua wrote · in English',
    'new.f1.wrote.es':   '→ Lingua wrote · in Spanish',
    'new.f1.lang.es':    'Spanish',
    'new.f1.lang.fr':    'French',
    'new.f1.lang.mix':   'Mixed ES + EN',
    'new.f1.lang.de':    'German',
    'new.f1.d1.said':    '"Oye, mañana no puedo ir a la reunión de las diez. ¿La movemos al jueves a la misma hora?"',
    'new.f1.d1.out':     "Hey — I can't make tomorrow's 10 o'clock. Could we move it to Thursday, same time?",
    'new.f1.d2.said':    '"Merci d\'avoir partagé le brief — j\'ai deux ou trois remarques mineures, rien de bloquant."',
    'new.f1.d2.out':     'Thanks for sharing the brief — I have a couple of minor notes, nothing blocking.',
    'new.f1.d3.said':    '"Lo de los KPIs lo cerramos en la weekly, but I want to push back on the deadline."',
    'new.f1.d3.out':     'Cerramos los KPIs en la weekly, pero quiero proponer mover la fecha de entrega.',
    'new.f1.d4.said':    '"Können wir den Vertrag bis Freitag abschließen? Ich brauche das für den Vorstand."',
    'new.f1.d4.out':     'Can we wrap up the contract by Friday? I need it for the board.',

    // Feature 2
    'new.f2.h.a':        'One sentence, ',
    'new.f2.h.em':       'every',
    'new.f2.h.b':        ' tone of voice.',
    'new.f2.b':          "Lingua reads the app you're writing in and adjusts the register automatically — tight in Slack, warm in Gmail, structured in Notion, blunt in your terminal. Nothing to configure.",
    'new.f2.youSaid':    'You said:',
    'new.f2.spoken':     '"Hey, the deploy is broken again, can someone take a look — I think it\'s the auth service, same thing as last Tuesday."',
    'new.f2.tone.casual':     'casual',
    'new.f2.tone.warm':       'warm',
    'new.f2.tone.structured': 'structured',
    'new.f2.tone.terse':      'terse',
    'new.f2.tone.polished':   'polished',
    'new.f2.slack':      "deploy's broken again 🙃 looks like auth-service — same as last Tuesday. who can grab it?",
    'new.f2.gmail':      'Hi team — quick heads-up that the deploy is failing again. From the symptoms, it looks like the auth service (same issue we hit last Tuesday). Could someone take a look when you have a moment?',
    'new.f2.notion.status':    'Status:',
    'new.f2.notion.statusV':   ' deploy failing.',
    'new.f2.notion.cause':     'Suspected cause:',
    'new.f2.notion.causeV':    ' auth service — same regression as last Tuesday.',
    'new.f2.notion.need':      'Need:',
    'new.f2.notion.needV':     ' an owner to investigate.',
    'new.f2.terminal':   '# deploy failing — likely auth-service (regression of 2026-04-21)',
    'new.f2.linkedin':   "Reposting context for the wider team: we're seeing a recurring failure on the auth service that's blocking deploys. Looking for an owner to dig in.",

    // Close
    'new.close.h.a':     'Both of these are ',
    'new.close.h.em':    'live',
    'new.close.h.b':     ' for everyone.',
    'new.close.b':       "No setting to flip, no separate plan. Update Lingua and start talking — translation kicks in when you switch languages, tone adapts the moment you're in a different app.",
    'new.close.cta':     'Back to home →',

    // About page
    'about.eyebrow':     'About Lingua',
    'about.lede.a':      "We're building a world where ",
    'about.lede.em':     'everyone',
    'about.lede.b':      ' can write at the speed of thought.',
    'about.intro.1':     "Lingua started with a simple frustration: the keyboard hasn't really changed in 150 years, but the way we think, speak, and work has. We type slower than we talk. We re-write the same things in five different apps. And for millions of people — those with limited mobility, dyslexia, RSI, or simply a brain that moves faster than ten fingers — the keyboard is more wall than window.",
    'about.intro.2':     "We're a small team of designers, engineers, and linguists who believe technology should bend to the human, not the other way around. So we built a voice interface that listens carefully, writes clearly, and disappears when you're done.",
    'about.sig':         'The Lingua team — hello@lingua.ai',
    'about.manifesto.1': "We don't think writing should be a tax on your time, your wrists, or your access to the world.",
    'about.manifesto.2.a': 'We think ',
    'about.manifesto.2.strong': "your voice is the most natural interface you'll ever own",
    'about.manifesto.2.b': ' — and the role of software is to honor it: to capture the nuance, polish the rough edges, and quietly hand back what you meant to say.',
    'about.manifesto.3': "That's the bar we measure ourselves against. Every feature, every release, every line of code.",
    'about.values.h':    'What we believe',
    'about.values.sub':  'Four principles we keep coming back to. They shape what we build, who we hire, and what we say no to.',
    'about.v1.h.a':      'Accessible ',
    'about.v1.h.em':     'by default',
    'about.v1.h.b':      ', not as a feature',
    'about.v1.b':        "Voice isn't a nice-to-have for the people who depend on it. We design Lingua so that anyone slowed down by a keyboard — through disability, injury, dyslexia, or language barrier — gets a first-class experience from day one. Accessibility lives in our roadmap, not in a checklist at the end of it.",
    'about.v2.h.a':      'Polish over ',
    'about.v2.h.em':     'perfection',
    'about.v2.h.b':      '',
    'about.v2.b':        'We catch your "ums," fix your typos, match your tone, and keep your meaning. The point is to give you back the version of yourself you would have written if you had thirty more minutes — not to sound like a robot.',
    'about.v3.h.a':      'Privacy is ',
    'about.v3.h.em':     'non-negotiable',
    'about.v3.h.b':      '',
    'about.v3.b':        "Your voice is yours. We process audio with care, train models responsibly, and never sell your data. Enterprise customers get the same controls we'd demand for ourselves: SSO, residency, retention windows, the lot.",
    'about.v4.h.a':      'Built to ',
    'about.v4.h.em':     'disappear',
    'about.v4.h.b':      '',
    'about.v4.b':        "The best tool is the one you forget you're using. Lingua works inside every app you already use — no copy-paste, no context switch, no second window. We measure success by how invisible we get.",
    'about.close.h.a':   'Want to help us build ',
    'about.close.h.em':  'this',
    'about.close.h.b':   '?',
    'about.close.b':     "We're a small, opinionated team — and we're hiring engineers, ML researchers, and accessibility specialists who want to put voice in the hands of everyone.",
    'about.close.cta':   'See open roles →',

    // Contact modal
    'contact.h.support':                'Contact support',
    'contact.h.sales':                  'Talk to sales',
    'contact.h.general':                'Get in touch',
    'contact.h.roles':                  'Tell us what you\'re working on',
    'contact.h.careers':                'Work with us',
    'contact.sub.a':                    'Sends to ',
    'contact.sub.b':                    ' as an email draft.',
    'contact.sub.careers':              'Tell us about you. We\'ll get back to you over email.',
    'contact.sub.private':              'We\'ll get back to you over email.',
    'contact.field.subject':            'Subject',
    'contact.field.name':               'Name',
    'contact.field.phone':              'Phone (optional)',
    'contact.field.message':            'Message',
    'contact.placeholder.phone':        '+1 555 0100',
    'contact.placeholder.subject.support': 'I need help with…',
    'contact.placeholder.subject.sales':   'Lingua for our team',
    'contact.placeholder.subject.general': 'Hi Lingua',
    'contact.placeholder.subject.roles':   'Hi — about a role',
    'contact.placeholder.subject.careers': 'Your full name',
    'contact.placeholder.message.support': 'What\'s happening, on which OS, and any steps to reproduce.',
    'contact.placeholder.message.sales':   'Tell us about your team — size, tools, what you want to solve.',
    'contact.placeholder.message.general': 'Say hi.',
    'contact.placeholder.message.roles':   'A few lines about you, what you build, and what you want next.',
    'contact.placeholder.message.careers': 'A few lines about you, what you\'ve built, and the kind of role you\'re after.',
    'contact.cancel':                   'Cancel',
    'contact.send':                     'Send',

    // Pricing page
    'pricing.eyebrow':                  'Beta pricing',
    'pricing.h.a':                      "You're ",
    'pricing.h.em':                     'early',
    'pricing.h.b':                      ". This price doesn't come back.",
    'pricing.sub':                      "Beta users who join now lock in the founders' price — forever. When we ship out of beta, it goes to $15/mo.",
    'pricing.toggle.monthly':           'Monthly',
    'pricing.toggle.annual':            'Annual',
    'pricing.toggle.discount':          '20% off',
    'pricing.tier.basic.tag':           'For individuals',
    'pricing.tier.basic.name':          'Lingua Basic',
    'pricing.tier.basic.price':         'Free',
    'pricing.tier.basic.priceSub':      'forever',
    'pricing.tier.basic.lede':          'The start of your productivity journey.',
    'pricing.tier.basic.cta':           'Get started',
    'pricing.tier.basic.note':          "You'll start with 30 days of Lingua Pro free.",
    'pricing.tier.basic.f.1':           '2,000 words / week on Mac and Windows',
    'pricing.tier.basic.f.2':           '1,000 words / week on iPhone',
    'pricing.tier.basic.f.3':           'Unlimited words on Android (limited time)',
    'pricing.tier.basic.f.4':           'Custom dictionary and snippets',
    'pricing.tier.basic.f.5':           '100+ languages',
    'pricing.tier.basic.f.6':           'Privacy mode (Zero Data Retention)',
    'pricing.tier.basic.f.7':           'HIPAA-ready',

    'pricing.tier.pro.tag':             'For individuals and teams',
    'pricing.tier.pro.name':            'Lingua Pro',
    'pricing.tier.pro.priceMonthly':    '$9',
    'pricing.tier.pro.priceAnnual':     '$89',
    'pricing.tier.pro.priceMonthlyOld': '$15',
    'pricing.tier.pro.priceAnnualOld':  '$144',
    'pricing.tier.pro.priceUnit':       '/ user / mo',
    'pricing.tier.pro.priceUnitAnnual': '/ user / yr',
    'pricing.tier.pro.priceSub.monthly':'billed monthly · beta price',
    'pricing.tier.pro.priceSub.annual': 'billed annually · beta price',
    'pricing.tier.pro.betaBadge':       'Locked in forever — no future price hikes',
    'pricing.tier.pro.betaHeadline':    'Lifetime beta pricing',
    'pricing.tier.pro.betaStamp':       'OFF',
    'pricing.tier.pro.lede':            'Everything in Basic, plus:',
    'pricing.tier.pro.cta':             'Get Lingua Pro',
    'pricing.tier.pro.popular':         'Most popular',
    'pricing.tier.pro.f.1':             'Unlimited words on Mac, Windows, iPhone and Android',
    'pricing.tier.pro.f.2':             'Prioritized support and feature requests',
    'pricing.tier.pro.f.3':             'Command mode for editing',
    'pricing.tier.pro.f.4':             'Early access to new features',
    'pricing.tier.pro.f.5':             'Team collaboration features',

    'pricing.tier.ent.tag':             'For teams that need advanced security & support',
    'pricing.tier.ent.name':            'Lingua Enterprise',
    'pricing.tier.ent.price':           'Contact us',
    'pricing.tier.ent.priceSub':        'billed annually',
    'pricing.tier.ent.lede':            'Everything in Pro for your team, plus:',
    'pricing.tier.ent.cta':             'Talk to sales',
    'pricing.tier.ent.f.1':             'Dedicated support',
    'pricing.tier.ent.f.2':             'SOC 2 Type II and ISO 27001 compliance',
    'pricing.tier.ent.f.3':             'Enforced HIPAA compliance',
    'pricing.tier.ent.f.4':             'Enforced Privacy Mode (Zero Data Retention)',
    'pricing.tier.ent.f.5':             'SSO / SAML',
    'pricing.tier.ent.f.6':             'Advanced usage dashboards',
    'pricing.tier.ent.f.7':             'Bulk pricing discounts',
    'pricing.tier.ent.f.8':             'Dedicated IT admin seats at no extra cost',

    'pricing.student.eyebrow':          'For students',
    'pricing.student.h':                '3 months free. Then 50% off, forever.',
    'pricing.student.b':                "If you're a student, your first three months are on us — after that you pay $7.50/mo instead of $15. While beta pricing is active ($9/mo), the student price is $4.50/mo. All you need is a university email.",
    'pricing.student.fine':             'New subscribers only. Requires a verified university email (.edu or institutional domain).',
    'pricing.student.cta':              'Claim student discount',

    'pricing.compare.h':                'Plans & features',
    'pricing.compare.col.basic':        'Basic',
    'pricing.compare.col.pro':          'Pro',
    'pricing.compare.col.ent':          'Enterprise',

    'pricing.compare.sec.devices':      'Device & platform',
    'pricing.compare.row.mac':          'Desktop (Mac)',
    'pricing.compare.row.win':          'Desktop (Windows)',
    'pricing.compare.row.ios':          'iPhone',
    'pricing.compare.row.android':      'Android',

    'pricing.compare.sec.typing':       'Effortless voice typing',
    'pricing.compare.row.dict':         'Custom dictionary',
    'pricing.compare.row.words':        'Word limit',
    'pricing.compare.cell.words.basic': '2,000/wk desktop · 1,000/wk iPhone · Unlimited Android',
    'pricing.compare.cell.unlimited':   'Unlimited',
    'pricing.compare.row.langs':        '100+ languages',
    'pricing.compare.row.priority':     'Prioritized feature requests',
    'pricing.compare.row.early':        'Early access to new features',

    'pricing.compare.sec.team':         'Team & collaboration',
    'pricing.compare.row.billing':      'Centralized billing',
    'pricing.compare.row.shared':       'Shared dictionary and snippets',
    'pricing.compare.row.support':      'Customer support',
    'pricing.compare.cell.support.basic':'Standard',
    'pricing.compare.cell.support.pro': 'Prioritized',
    'pricing.compare.cell.support.ent': 'Dedicated',
    'pricing.compare.row.dashboards':   'Team usage dashboards',
    'pricing.compare.cell.dash.pro':    'Basic',
    'pricing.compare.cell.dash.ent':    'Advanced',

    'pricing.compare.sec.security':     'Security & compliance',
    'pricing.compare.row.privacy':      'Privacy mode (Zero Data Retention)',
    'pricing.compare.cell.enforced':    'Enforced',
    'pricing.compare.row.iso':          'ISO 27001 and SOC 2 Type II',
    'pricing.compare.row.sso':          'SSO / SAML',
    'pricing.compare.row.adminctl':     'Admin controls',
    'pricing.compare.row.msa':          'MSA & DPA',
    'pricing.compare.row.hipaa':        'HIPAA-ready',

    'pricing.calc.h':                   'Calculate your savings',
    'pricing.calc.hours':               'I spend',
    'pricing.calc.hoursUnit':           'hours typing a day',
    'pricing.calc.wordsNote':           "That's about {words} words per day.",
    'pricing.calc.rate':                'My time is worth',
    'pricing.calc.rateUnit':            '/ hour',
    'pricing.calc.savings':             "Monthly, you'll save",
    'pricing.calc.row.hoursTyping':     'Hours spent typing',
    'pricing.calc.row.hoursSaved':      'Hours saved monthly',
    'pricing.calc.row.timeValue':       'Time value saved',
    'pricing.calc.row.cost':            'Lingua Pro monthly cost',

    'pricing.faq.h':                    'Frequently asked questions',
    'pricing.faq.q1':                   'How do I upgrade from Basic to Pro?',
    'pricing.faq.a1':                   "When you sign up for Lingua, you get a 30-day free trial of Pro. To upgrade, open the app and click Try Lingua Pro. You can also find Plan & Billing under Settings.",
    'pricing.faq.q2':                   'Is there a free trial or free plan available?',
    'pricing.faq.a2':                   "Yes. All new individual accounts include a 30-day Pro trial — after the trial, you'll convert to Lingua Basic (our free plan) unless you upgrade. Each teammate you invite to a team also gets their own 30-day Pro trial.",
    'pricing.faq.q3':                   'Can I change or cancel my subscription at any time?',
    'pricing.faq.a3':                   'Yes. You can manage your subscription under Plan & Billing in the Lingua desktop app. If you need help, reach out via the Support portal.',
    'pricing.faq.q4':                   'Do you offer discounts for specific groups?',
    'pricing.faq.a4':                   'Yes — discounted Lingua Pro for students, educators and non-profit organizations.',
    'pricing.faq.q5':                   'Can I use Lingua for my whole team?',
    'pricing.faq.a5':                   'Yes. Lingua Pro supports both individuals and teams: no minimum seats, shared dictionary and snippets, centralized billing, basic usage dashboards. For SSO/SAML, advanced compliance, advanced dashboards or bulk discounts, talk to our Sales team about Enterprise.',
  },

  es: {
    // Nav
    'nav.menu.company':   'Empresa',
    'nav.menu.product':   'Producto',
    'nav.menu.resources': 'Recursos',
    'nav.about':          'Sobre nosotros',
    'nav.careers':        'Empleo',
    'nav.affiliates':     'Afiliados',
    'nav.whatsnew':       'Novedades',
    'nav.usecases':       'Casos de uso',
    'nav.pricing':        'Precios',
    'nav.business':       'Para empresas',
    'nav.support':        'Soporte',
    'nav.sales':          'Ventas',
    'nav.typingtest':     'Test de mecanografía',
    'nav.login':          'Iniciar sesión',
    'nav.contact':        'Contacto',
    'nav.cta':            'Descargar',

    // Hero
    'hero.eyebrow':       'Escribe con tu voz — ¿a quién le gusta teclear?',
    'hero.title.start':   'no ',
    'hero.title.typo':    'tcedaol',
    'hero.title.target':  'teclado',
    'hero.title.tail.more': '',
    'hero.title.tail.em':   'escribas',
    'hero.title.tail.typo': 'esbric',
    'hero.title.tail.dot':  '.',
    'hero.sub':           'Lingua es la nueva forma de escribir: tú hablas y tu ordenador lo convierte en texto limpio y bien formateado.\nSí, en cualquier app.',
    'hero.platform.mac':     'Mac',
    'hero.platform.windows': 'Windows',
    'hero.cta.test':      'Prueba el test',
    'hero.cta.try':       'Prueba Lingua',
    'hero.fine':          'Gratis para empezar. Sin tarjeta. Mac y Windows.',
    'hero.transcript.app': 'Transcribiendo en Notas',
    'hero.t.0':  'Lingua me ayuda a fluir cuando escribo sin verme limitada por mi escritura.',
    'hero.t.1':  'Escribir en mi ordenador ha pasado a ser fácil.',
    'hero.t.2':  'Cuando investigo con la IA, Lingua me ayuda a ahorrar horas dando contexto.',
    'hero.t.3':  'Con el tiempo que he ahorrado al no tener que escribir lentamente, me ha salido a cuenta todo el año en solo una semana.',
    'hero.t.4':  'Responder a los mails de los clientes ha pasado de ser un infierno a ser como tener una conversación normal con ellos.',
    'hero.t.5':  'Gracias a terminar antes mis informes médicos con Lingua, ahora puedo cenar con mi familia.',
    'hero.t.6':  'Enviar notas personalizadas a mis alumnos. Es algo que me ha permitido Lingua y que si tuviera que escribir me llevaría horas.',
    'hero.t.7':  'Ha multiplicado mi productividad 2x.',
    'hero.t.8':  'Cuando tengo el cerebro frito y quiero escribir en inglés, hablo en castellano y Lingua se encarga de traducir por mí.',
    'hero.t.9':  'Mi herramienta más importante después de la cámara.',
    'hero.t.10': 'Acta en 5 min en lugar de 30.',
    'hero.t.11': '3 → 4 artículos a la semana sin morir.',
    'hero.t.12': 'Mantener un registro de todas mis acciones para el equipo de mi ordenador nunca fue tan fácil.',
    'hero.t.13': 'Lingua me permite no tener que perder tiempo en teclear y ganar tiempo para hacer lo que más me gusta, crear.',
    'hero.t.14': 'Triplicado el output semanal.',
    'hero.t.15': 'Esto me ha salvado la vida. Teclear te deja los dedos destrozados.',
    'hero.t.16': 'El mejor regalo que le puedes hacer a tu salud mental.',
    'hero.t.17': 'El motor invisible de mi productividad.',
    'hero.t.18': '10 horas a la semana recuperadas.',
    'hero.t.19': 'Lo mejor que le ha pasado a la industria del guion.',

    // CTA band
    'cta.title.a':  'Empieza a ',
    'cta.title.em': 'hablar',
    'cta.title.b':  '.',
    'cta.body':     'Lingua funciona en cualquier app que ya usas. Gratis para empezar.',
    'cta.try':      'Prueba Lingua',
    'cta.download': 'Descargar',
    'cta.fine':     'Mac y Windows · más de 60 idiomas',

    // Apps section
    'apps.title.a':  'Escribe más rápido en ',
    'apps.title.em': 'todas',
    'apps.title.b':  ' tus apps.',
    'apps.sub':      'Lingua funciona en todo el sistema. Habla en cualquier app, en cualquier ventana: tus palabras aparecen donde está el cursor.',
    'apps.any.eb':   'Cualquier app',
    'apps.any.sub':  'Donde parpadee el cursor',

    // Tone block
    'tone.eyebrow':       'Reconoce el contexto',
    'tone.title.a':       'Ya sabe ',
    'tone.title.em':      'dónde',
    'tone.title.b':       ' estás escribiendo.',
    'tone.body':          'Las mismas palabras dichas — Lingua lee la app y ajusta el tono, la longitud y el formato para que el mensaje encaje.',
    'tone.said.label':    'Has dicho: ',
    'tone.said.text':     '"di al equipo que el lanzamiento se mueve al viernes"',
    'tone.row.slack':     'equipo — lanzamiento se mueve al viernes 🤝',
    'tone.row.gmail':     'Aviso rápido: el lanzamiento pasa al viernes. Adjunto el brief actualizado.',
    'tone.row.linkedin':  'Os aviso — el lanzamiento se mueve al viernes para un mejor reveal.',
    'tone.row.whatsapp':  'lanzamiento → viernes 👍',
    'tone.pill.casual':       'casual',
    'tone.pill.formal':       'formal',
    'tone.pill.professional': 'profesional',
    'tone.pill.brief':        'breve',

    // Personas
    'personas.eyebrow':         'Pensado para ti',
    'personas.title.a':         'Lingua está pensado ',
    'personas.title.em':        'para ti',
    'personas.title.b':         '.',
    'personas.heading.a':       'Hecho para ',
    'personas.cta.learn':       'Saber más',
    'personas.cta.download':    'Descargar',
    'personas.consultants.tab': 'Consultoría',
    'personas.consultants.em':  'consultores',
    'personas.consultants.body':'Presentaciones, memos y emails a cliente — redactados en lo que tardas en bajar a por café.',
    'personas.creators.tab':    'Creadores',
    'personas.creators.em':     'creadores',
    'personas.creators.body':   'Captura ideas en bruto al ritmo al que se te ocurren. Lingua aguanta el chorro.',
    'personas.devs.tab':        'Desarrollo',
    'personas.devs.em':         'desarrolladores',
    'personas.devs.body':       'PRs, comentarios y changelogs — narrados, no tecleados. Sin salir del editor.',
    'personas.sales.tab':       'Ventas',
    'personas.sales.em':        'equipos de ventas',
    'personas.sales.body':      'Seguimientos mientras caminas entre llamadas. Mismo tono, misma velocidad, sin atrasos.',
    'personas.students.tab':    'Estudiantes',
    'personas.students.em':     'estudiantes',
    'personas.students.body':   'Apuntes y trabajos sin dolor de muñeca. Lingua escribe mientras tú piensas.',

    // Values
    'values.eyebrow':   'Por qué Lingua',
    'values.title':     'La voz debería ser la forma más natural de usar un ordenador.',
    'values.1.eb':      '01',
    'values.1.t':       'Hecho para ',
    'values.1.em':      'cada app',
    'values.1.body':    'Lingua funciona allí donde escribes — sin plugins, sin integraciones, sin fricción.',
    'values.2.eb':      '02',
    'values.2.t':       'Verdadero ',
    'values.2.em':      'oficio',
    'values.2.body':    'Puntuación, mayúsculas, párrafos. Los pequeños detalles que hacen que hablar parezca escribir.',
    'values.3.eb':      '03',
    'values.3.t':       'Pensado para ',
    'values.3.em':      'personas',
    'values.3.body':    'Pausas, muletillas, cambios de idea — Lingua entiende cómo habla la gente de verdad.',
    'values.4.eb':      '04',
    'values.4.t':       'Privado por ',
    'values.4.em':      'defecto',
    'values.4.body':    'En tu dispositivo siempre que se pueda. Tu voz nunca entrena un modelo. Tú mandas.',

    // Love letters
    'love.eyebrow':  'Querido por quienes escriben',
    'love.title.a':  'Unas ',
    'love.title.em': 'cartas de amor',
    'love.title.b':  '.',
    'love.who1':  'Tara',
    'love.role1': 'Diseñadora',
    'love.q1':    'Dejé de temer el correo. Lingua acierta el tono sin más.',
    'love.who2':  'Rahul',
    'love.role2': 'PM',
    'love.q2':    'El doble de palabras con la mitad de muñeca. Escribo más porque me cuesta menos.',
    'love.who3':  'Suzanne',
    'love.role3': 'Escritora',
    'love.q3':    'Es lo más cercano a pensar directamente sobre la página que he probado.',

    // Footer
    'footer.col.company':   'Empresa',
    'footer.col.product':   'Producto',
    'footer.col.resources': 'Recursos',
    'footer.col.contact':   'Contacto',
    'footer.twitter':       'X / Twitter',
    'footer.linkedin':      'LinkedIn',
    'footer.copy':          '© 2025 Lingua. Hecho a mano.',
    'footer.terms':         'Términos',
    'footer.privacy':       'Privacidad',
    'footer.data':          'Datos',





    // Typing test
    'tt.back':           '← Volver a Lingua',
    'tt.eyebrow':        'El test de mecanografía',
    'tt.h.a':            '¿A qué velocidad ',
    'tt.h.em':           'tecleas',
    'tt.h.b':            ' realmente?',
    'tt.sub':            'Teclea la frase de abajo. El reloj arranca con la primera tecla correcta. Los errores no cuentan — no puedes pasar de ellos.',
    'tt.phrase':         "Nunca me había dado cuenta, pero escribir en el teclado es mucho más lento que hablar. ¿Cómo sería mi vida si no tuviera que teclear tanto?",
    'tt.status.ready':   'LISTO · empieza a teclear',
    'tt.status.recording': 'GRABANDO',
    'tt.status.done':    'HECHO',
    'tt.chars':          'car.',
    'tt.hint.done.a':    'Pulsa ',
    'tt.hint.done.b':    ' para volver a probar',
    'tt.hint.go':        'Empieza a teclear — el reloj arranca con la primera tecla correcta',
    'tt.scrollcue':      'Tus resultados, abajo',
    'tt.unit':           'palabras / min',
    'tt.scenario.slow':  'Lingua no es un lujo — es recuperar tu día.',
    'tt.scenario.mid':   'Hasta los buenos mecanógrafos dejan horas sobre la mesa cada semana.',
    'tt.scenario.fast':  'Impresionante. Ahora imagina qué pasa cuando dejas de teclear del todo.',
    'tt.lingua.cap.a':   'Dictado con Lingua — unas ',
    'tt.lingua.cap.b':   '× más rápido.',
    'tt.saved.a':        'Has tardado ',
    'tt.saved.took':     ' segundos',
    'tt.saved.b':        ' en teclearlo. Dicho en voz alta: ',
    'tt.saved.spoken':   ' segundos',
    'tt.saved.c':        '. ',
    'tt.saved.bold.a':   'Lingua te habría devuelto ',
    'tt.saved.bold.b':   ' segundos — en esta sola frase.',
    'tt.bar.you':        'Tú, ahora mismo',
    'tt.bar.avg':        'Mecanógrafo medio',
    'tt.bar.lingua':     'Dictado con Lingua',
    'tt.bar.unit':       'ppm',
    'tt.calc.h':         'Ahora multiplícalo',
    'tt.calc.lede.a':    'Si tecleas ',
    'tt.calc.lede.em':   'unas ',
    'tt.calc.lede.h':    'hora',
    'tt.calc.lede.hs':   'horas',
    'tt.calc.lede.b':    ' al día a tu velocidad, esto es lo que Lingua te devuelve cada semana:',
    'tt.calc.label':     'Horas tecleando al día',
    'tt.calc.unit':      'horas / semana ahorradas',
    'tt.cta.dl':         'Descargar Lingua — gratis',
    'tt.cta.again':      'Probar de nuevo',

    // Use cases page
    'uc.eyebrow':           'Casos de uso',
    'uc.hero.h.a':          'Pensado para ',
    'uc.hero.h.em':         'cómo',
    'uc.hero.h.b':          ' trabajas de verdad.',
    'uc.hero.sub':          'Cinco trabajos que Lingua hace todos los días, con los emails y las notas que la gente envía de verdad. Sin demos, sin relleno de marketing — el mismo texto que escribirías tú, solo que más rápido.',
    'uc.jump.consultants':  'Consultoría',
    'uc.jump.creators':     'Creadores',
    'uc.jump.devs':         'Desarrollo',
    'uc.jump.sales':        'Ventas',
    'uc.jump.students':     'Estudiantes',
    'uc.worksIn':           'Funciona en',

    // Consultants
    'uc.cons.tag':          'Para consultoría',
    'uc.cons.h.a':          'Factura las horas. ',
    'uc.cons.h.em':         'Sáltate',
    'uc.cons.h.b':          ' la mecanografía.',
    'uc.cons.sub':          'Decks, memos para el cliente, recaps tras la reunión — el peaje que se come tus horas facturables. Resuelve los seguimientos hablando, dicta tus frameworks directamente sobre la slide y vete de la oficina antes de que se ponga el sol.',
    'uc.cons.e1.before':    'Justo al salir de la reunión',
    'uc.cons.e1.b.a':       '"Resume el workshop de Lufthansa — tres entregables, responsables, fechas. Envíalo a ',
    'uc.cons.e1.b.em':      'olivia@',
    'uc.cons.e1.b.b':       ' con copia al partner."',
    'uc.cons.e2.before':    'En la sala VIP del aeropuerto',
    'uc.cons.e2.b':         'Dicta un framework 2×2 para el próximo steerco — Lingua lo deja ya formateado en las notas de la slide.',
    'uc.cons.e3.before':    'Viernes, Slack al equipo de staffing',
    'uc.cons.e3.s':         'aviso q la próxima semana voy a 60% solo lun/mar, luego offsite',
    'uc.cons.e3.em':        'Aviso de capacidad: la próxima semana estoy al 60 % (lunes y martes), y de miércoles a viernes en offsite.',
    'uc.cons.stat':         '2,4 h/día',
    'uc.cons.statLbl':      'tiempo medio que recuperan los consultores en la beta de Lingua',
    'uc.cons.demoTitle':    'Recap — workshop Lufthansa.docx',
    'uc.cons.live':         'Lingua dictando · español → inglés',
    'uc.cons.draft':        `Recap: workshop de marca Q3 con Lufthansa\nResponsable: A. Méndez · 12 mar\n\nTres cosas que cerramos para el lunes:\n\n1. Afinar el posicionamiento en torno a "la red con la que vuelves a casa". Olivia se encarga de reescribir el deck.\n\n2. Quitar el pilar de fidelización del plan 2026 — solapa con el equipo de millas.`,

    // Creators
    'uc.cre.tag':           'Para creadores',
    'uc.cre.h.a':           'Responde a ',
    'uc.cre.h.em':          'todos',
    'uc.cre.h.b':           '. Con tu voz.',
    'uc.cre.sub':           'Las ideas llegan rápido, pero ejecutar es lento. Pasa volando por los DMs sin leer, los comentarios y los borradores de posts hablando. Crea más, escribe menos.',
    'uc.cre.e1.before':     'Bandeja a tope',
    'uc.cre.e1.b.a':        'Pasea mientras desayunas — Lingua responde a ',
    'uc.cre.e1.b.em':       'treinta DMs sin leer en Instagram',
    'uc.cre.e1.b.b':        ' con tu tono y deja cada uno listo para enviar de un toque.',
    'uc.cre.e2.before':     'Caption para el vídeo',
    'uc.cre.e2.b':          'Cuenta la idea una vez. Recibe un hook ajustado de dos líneas, tres hashtags y un caption largo de 60 palabras — eliges el que encaja.',
    'uc.cre.e3.before':     'Pitch de marca en el correo',
    'uc.cre.e3.s':          'gracias pero el caché es muy bajo',
    'uc.cre.e3.em':         'Gracias por la propuesta. La tarifa está por debajo de mi rango habitual — encantada de mandar una contraoferta si hay flexibilidad en derechos de uso.',
    'uc.cre.stat':          '5×',
    'uc.cre.statLbl':       'más rápido llegar a inbox-zero entre IG, TikTok y email — medido en la beta de creadores',
    'uc.cre.demoTitle':     'Bandeja · 3 sin leer',
    'uc.cre.dm1.who':       'Maya R.',
    'uc.cre.dm1.msg':       'me ha encantado el último vídeo — ¿lo puedo compartir en nuestra newsletter?',
    'uc.cre.dm1.reply':     'Sí, claro — adelante. Pásame el enlace cuando salga y lo recomparto.',
    'uc.cre.dm2.who':       'Felipe',
    'uc.cre.dm2.msg':       'oye, ¿sigues haciendo el taller de iluminación en mayo?',
    'uc.cre.dm2.reply':     '¡Hola! Sí, el 18 de mayo, quedan dos plazas. ¿Te guardo una?',
    'uc.cre.dm3.who':       'Studio Ono',
    'uc.cre.dm3.msg':       'Un favor rápido: ¿te animarías a co-presentar el episodio 12?',
    'uc.cre.dm3.reply':     'Tienta — depende de las fechas. Pásame el calendario de grabación y lo miro.',

    // Developers
    'uc.dev.tag':           'Para desarrollo',
    'uc.dev.h.a':           'Sigue en ',
    'uc.dev.h.em':          'flow',
    'uc.dev.h.b':           '. Y entrega igual.',
    'uc.dev.sub':           'Dicta en lenguaje natural y deja que Lingua traduzca — ideal para Cursor, VS Code o donde construyas. Desde el commit hasta el refactor, sin salir del flow.',
    'uc.dev.e1.before':     'Dentro de Cursor',
    'uc.dev.e1.b.a':        '"Refactoriza este ',
    'uc.dev.e1.b.em1':      'useEffect',
    'uc.dev.e1.b.b':        ' a un hook propio llamado ',
    'uc.dev.e1.b.em2':      'useUsers',
    'uc.dev.e1.b.c':        ', que devuelva loading y error." → Lingua se lo entrega a tu IA como un prompt limpio, sin erratas.',
    'uc.dev.e2.before':     'Hora del commit',
    'uc.dev.e2.b.a':        '"',
    'uc.dev.e2.b.em':       'fix: gestionar carrito vacío en checkout — saltar la llamada de totales cuando items es 0',
    'uc.dev.e2.b.b':        '". Una frase, formato conventional commits, hecho.',
    'uc.dev.e3.before':     'Revisión de PR un día complicado',
    'uc.dev.e3.b':          'Recorre el diff hablando; Lingua deja una review estructurada con marcadores fichero:línea en el cuadro de comentario.',
    'uc.dev.stat':          '120 ppm',
    'uc.dev.statLbl':       'dictar prompts gana a teclearlos — y es más amable con las muñecas',
    'uc.dev.demoTitle':     '~ / users.tsx — Cursor',
    'uc.dev.dictation':     'añade un useEffect que haga fetch a /api/users al montar y guarde el resultado en estado, con un try-catch alrededor',

    // Sales
    'uc.sales.tag':         'Para ventas',
    'uc.sales.h.a':         'Da seguimiento mientras está ',
    'uc.sales.h.em':        'caliente',
    'uc.sales.h.b':         '.',
    'uc.sales.sub':         'Seguimientos lentos, deals perdidos. Manda follow-ups inmediatos tras la reunión, personaliza el outreach y afina tu pitch — sin teclear una palabra.',
    'uc.sales.e1.before':   'Saliendo de la demo',
    'uc.sales.e1.b':        '"Manda a Priya el one-pager de precios, el doc de integraciones y reserva un hueco el jueves a las 14 h." Lingua deja los tres en cola antes de que llegues al ascensor.',
    'uc.sales.e2.before':   'Outreach en frío con voz real',
    'uc.sales.e2.b.a':      'Habla un opener personalizado; Lingua lo convierte en ',
    'uc.sales.e2.b.em':     '20 variantes',
    'uc.sales.e2.b.b':      ' para tu secuenciador — mismo gancho, datos distintos por cuenta.',
    'uc.sales.e3.before':   'Registrando la llamada',
    'uc.sales.e3.s':        'cl quiere piloto, empuja 6 meses, atascado en compras',
    'uc.sales.e3.em':       'El cliente acepta un piloto de 6 meses pendiente de revisión por compras. Próximo paso: introducir a seguridad el lunes.',
    'uc.sales.stat':        '38 %',
    'uc.sales.statLbl':     'más respuesta cuando los seguimientos salen en la primera hora tras la llamada',
    'uc.sales.demoTitle':   'Cola de Lingua · enviando ahora',
    'uc.sales.m1.who':      'Priya · Acme',
    'uc.sales.m1.sub':      'Seguimiento a la demo — tres números de tu equipo',
    'uc.sales.m2.who':      'Jordan · Northwind',
    'uc.sales.m2.sub':      'Recap y siguiente paso: arrancar el piloto en la semana 2',
    'uc.sales.m3.who':      'Hira · Globex',
    'uc.sales.m3.sub':      'Encantada con la conversación — te envío el pricing que pediste',
    'uc.sales.m4.who':      'Tom · Initech',
    'uc.sales.m4.sub':      'Respuesta rápida a tu pregunta de churn + un 1-pager',
    'uc.sales.counterLbl':  'seguimientos enviados hoy · desde las 9:04',

    // Students
    'uc.stu.tag':           'Para estudiantes',
    'uc.stu.h.a':           'Del ',
    'uc.stu.h.em':          'aula',
    'uc.stu.h.b':           ' a la página.',
    'uc.stu.sub':           'Páginas en blanco y entregas que aprietan: Lingua te cubre. Captura clases, redacta cartas de motivación, rompe el bloqueo — todo hablando.',
    'uc.stu.e1.before':     'En la clase de las 9',
    'uc.stu.e1.b.a':        'Susurra mientras pasa la slide; Lingua te deja una nota limpia con bullets en ',
    'uc.stu.e1.b.em':       'Notion',
    'uc.stu.e1.b.b':        ', con la fecha y el profesor etiquetados.',
    'uc.stu.e2.before':     'Carta de motivación, diez minutos antes del deadline',
    'uc.stu.e2.b':          'Cuenta tu historia durante dos minutos; Lingua devuelve un borrador de 250 palabras, un opener específico para el puesto y tres sugerencias de "qué quitar".',
    'uc.stu.e3.before':     'Slack del trabajo en grupo',
    'uc.stu.e3.s':          '¿alguien hace las slides y yo grabo la voz?',
    'uc.stu.e3.em':         '¿Os encargáis vosotros de las slides? Yo grabo la voz para el jueves — solo necesito el guion el día antes.',
    'uc.stu.stat':          '3 h/semana',
    'uc.stu.statLbl':       'tiempo medio de lectura y escritura recuperado por estudiantes en programas piloto',
    'uc.stu.demoTitle':     'Ética 201 — Notas clase 4',
    'uc.stu.note1':         'Kant: imperativos — categórico vs. hipotético',
    'uc.stu.note2':         'Categórico = incondicional, p. ej. "no mentir"',
    'uc.stu.note3':         'Hipotético = medio-fin, p. ej. "estudiar para aprobar"',
    'uc.stu.note4':         'Crítica: ¿demasiado rígido? dilema del tranvía, etc.',
    'uc.stu.note5':         'Examen el viernes — foco en §2 de la Fundamentación',

    // What's new page
    'new.eyebrow':       'Novedades · Primavera 2026',
    'new.lede.a':        'Habla en ',
    'new.lede.em':       'cualquier',
    'new.lede.b':        ' idioma. Suena como lo dirías tú.',
    'new.intro':         'Dos cosas nuevas que puedes hacer con Lingua hoy. La misma idea de siempre — hablas con naturalidad, recibes texto limpio — ahora con pasaporte y sentido del contexto.',

    // Feature 1
    'new.f1.tag':        'Nueva función',
    'new.f1.h.a':        'Habla un idioma, ',
    'new.f1.h.em':       'escribe',
    'new.f1.h.b':        ' otro.',
    'new.f1.b':          'Dicta en el idioma en el que piensas. Lingua escribe en el idioma que necesitas — al instante, en cualquier app, con el matiz de un traductor de verdad y no uno literal.',
    'new.f1.youSaid':    'Dijiste',
    'new.f1.wrote.en':   '→ Lingua escribió · en inglés',
    'new.f1.wrote.es':   '→ Lingua escribió · en español',
    'new.f1.lang.es':    'Español',
    'new.f1.lang.fr':    'Francés',
    'new.f1.lang.mix':   'Mezcla ES + EN',
    'new.f1.lang.de':    'Alemán',
    'new.f1.d1.said':    '"Oye, mañana no puedo ir a la reunión de las diez. ¿La movemos al jueves a la misma hora?"',
    'new.f1.d1.out':     "Hey — I can't make tomorrow's 10 o'clock. Could we move it to Thursday, same time?",
    'new.f1.d2.said':    '"Merci d\'avoir partagé le brief — j\'ai deux ou trois remarques mineures, rien de bloquant."',
    'new.f1.d2.out':     'Gracias por compartir el brief — tengo un par de comentarios menores, nada bloqueante.',
    'new.f1.d3.said':    '"Lo de los KPIs lo cerramos en la weekly, but I want to push back on the deadline."',
    'new.f1.d3.out':     'Cerramos los KPIs en la weekly, pero quiero proponer mover la fecha de entrega.',
    'new.f1.d4.said':    '"Können wir den Vertrag bis Freitag abschließen? Ich brauche das für den Vorstand."',
    'new.f1.d4.out':     '¿Podemos cerrar el contrato antes del viernes? Lo necesito para el consejo.',

    // Feature 2
    'new.f2.h.a':        'Una frase, ',
    'new.f2.h.em':       'cualquier',
    'new.f2.h.b':        ' tono.',
    'new.f2.b':          'Lingua lee la app en la que estás escribiendo y ajusta el registro automáticamente — directo en Slack, cercano en Gmail, estructurado en Notion, escueto en la terminal. Sin configurar nada.',
    'new.f2.youSaid':    'Dijiste:',
    'new.f2.spoken':     '"Eh, el deploy está roto otra vez, ¿alguien puede mirarlo? Creo que es el servicio de auth, lo mismo del martes pasado."',
    'new.f2.tone.casual':     'informal',
    'new.f2.tone.warm':       'cercano',
    'new.f2.tone.structured': 'estructurado',
    'new.f2.tone.terse':      'escueto',
    'new.f2.tone.polished':   'pulido',
    'new.f2.slack':      'el deploy está roto otra vez 🙃 parece auth-service — lo mismo del martes pasado. ¿quién lo coge?',
    'new.f2.gmail':      'Hola equipo — un aviso rápido: el deploy vuelve a fallar. Por los síntomas, parece el servicio de auth (el mismo problema del martes pasado). ¿Alguien podría echarle un ojo cuando pueda?',
    'new.f2.notion.status':    'Estado:',
    'new.f2.notion.statusV':   ' deploy fallando.',
    'new.f2.notion.cause':     'Causa probable:',
    'new.f2.notion.causeV':    ' servicio de auth — misma regresión del martes pasado.',
    'new.f2.notion.need':      'Necesitamos:',
    'new.f2.notion.needV':     ' un responsable que lo investigue.',
    'new.f2.terminal':   '# deploy fallando — probable auth-service (regresión del 2026-04-21)',
    'new.f2.linkedin':   'Repongo contexto para el equipo: vemos un fallo recurrente en el servicio de auth que está bloqueando los deploys. Busco a alguien que se ponga con ello.',

    // Close
    'new.close.h.a':     'Las dos están ',
    'new.close.h.em':    'activas',
    'new.close.h.b':     ' para todos.',
    'new.close.b':       'Sin ajustes que tocar ni plan aparte. Actualiza Lingua y empieza a hablar — la traducción se activa al cambiar de idioma, el tono se adapta en cuanto cambias de app.',
    'new.close.cta':     'Volver a inicio →',

    // About page
    'about.eyebrow':     'Sobre Lingua',
    'about.lede.a':      'Estamos construyendo un mundo en el que ',
    'about.lede.em':     'todos',
    'about.lede.b':      ' puedan escribir a la velocidad del pensamiento.',
    'about.intro.1':     'Lingua nació de una frustración sencilla: el teclado no ha cambiado en 150 años, pero la forma en que pensamos, hablamos y trabajamos sí. Tecleamos más lento de lo que hablamos. Reescribimos lo mismo en cinco apps distintas. Y para millones de personas — con movilidad reducida, dislexia, lesiones por esfuerzo o, sencillamente, una cabeza que va más rápido que diez dedos — el teclado es más muro que ventana.',
    'about.intro.2':     'Somos un equipo pequeño de diseñadores, ingenieros y lingüistas que creemos que la tecnología debe doblegarse al ser humano, y no al revés. Por eso hemos construido una interfaz de voz que escucha con atención, escribe con claridad y desaparece cuando terminas.',
    'about.sig':         'El equipo de Lingua — hello@lingua.ai',
    'about.manifesto.1': 'No creemos que escribir deba ser un impuesto sobre tu tiempo, tus muñecas o tu acceso al mundo.',
    'about.manifesto.2.a': 'Creemos que ',
    'about.manifesto.2.strong': 'tu voz es la interfaz más natural que tendrás jamás',
    'about.manifesto.2.b': ', y el papel del software es honrarla: capturar el matiz, pulir los bordes y devolverte, sin ruido, lo que querías decir.',
    'about.manifesto.3': 'Esa es la vara con la que nos medimos. Cada función, cada release, cada línea de código.',
    'about.values.h':    'Lo que creemos',
    'about.values.sub':  'Cuatro principios a los que volvemos siempre. Definen qué construimos, a quién contratamos y a qué decimos que no.',
    'about.v1.h.a':      'Accesible ',
    'about.v1.h.em':     'por defecto',
    'about.v1.h.b':      ', no como añadido',
    'about.v1.b':        'La voz no es algo opcional para quienes dependen de ella. Diseñamos Lingua para que cualquier persona a quien el teclado le ralentice — por discapacidad, lesión, dislexia o barrera idiomática — tenga una experiencia de primera desde el día uno. La accesibilidad vive en nuestra hoja de ruta, no en un checklist al final.',
    'about.v2.h.a':      'Pulido frente a ',
    'about.v2.h.em':     'perfección',
    'about.v2.h.b':      '',
    'about.v2.b':        'Quitamos los «eh», corregimos las erratas, ajustamos el tono y mantenemos el sentido. La idea es devolverte la versión de ti que habrías escrito con treinta minutos más, no que suenes a robot.',
    'about.v3.h.a':      'La privacidad ',
    'about.v3.h.em':     'no se negocia',
    'about.v3.h.b':      '',
    'about.v3.b':        'Tu voz es tuya. Procesamos el audio con cuidado, entrenamos modelos con responsabilidad y nunca vendemos tus datos. Las cuentas empresariales tienen los mismos controles que exigiríamos para nosotros: SSO, residencia, ventanas de retención, todo.',
    'about.v4.h.a':      'Hecho para ',
    'about.v4.h.em':     'desaparecer',
    'about.v4.h.b':      '',
    'about.v4.b':        'La mejor herramienta es la que olvidas estar usando. Lingua funciona dentro de cada app que ya usas — sin copiar y pegar, sin cambio de contexto, sin segunda ventana. Medimos el éxito por lo invisibles que llegamos a ser.',
    'about.close.h.a':   '¿Quieres ayudarnos a construir ',
    'about.close.h.em':  'esto',
    'about.close.h.b':   '?',
    'about.close.b':     'Somos un equipo pequeño y con criterio — y estamos contratando ingenieros, investigadores de ML y especialistas en accesibilidad que quieran poner la voz en manos de todo el mundo.',
    'about.close.cta':   'Ver puestos abiertos →',

    // Contact modal
    'contact.h.support':                'Contactar con soporte',
    'contact.h.sales':                  'Hablar con ventas',
    'contact.h.general':                'Ponte en contacto',
    'contact.h.roles':                  'Cuéntanos en qué andas',
    'contact.h.careers':                'Trabaja con nosotros',
    'contact.sub.a':                    'Se envía a ',
    'contact.sub.b':                    ' como un borrador de email.',
    'contact.sub.careers':              'Cuéntanos sobre ti. Te responderemos por email.',
    'contact.sub.private':              'Te responderemos por email.',
    'contact.field.subject':            'Asunto',
    'contact.field.name':               'Nombre',
    'contact.field.phone':              'Teléfono (opcional)',
    'contact.field.message':            'Mensaje',
    'contact.placeholder.phone':        '+34 600 000 000',
    'contact.placeholder.subject.support': 'Necesito ayuda con…',
    'contact.placeholder.subject.sales':   'Lingua para nuestro equipo',
    'contact.placeholder.subject.general': 'Hola Lingua',
    'contact.placeholder.subject.roles':   'Hola, sobre un puesto',
    'contact.placeholder.subject.careers': 'Tu nombre completo',
    'contact.placeholder.message.support': 'Qué pasa, en qué sistema operativo y cómo reproducirlo.',
    'contact.placeholder.message.sales':   'Cuéntanos del equipo — tamaño, herramientas, qué quieres resolver.',
    'contact.placeholder.message.general': 'Saluda.',
    'contact.placeholder.message.roles':   'Unas líneas sobre ti, lo que construyes y lo que buscas.',
    'contact.placeholder.message.careers': 'Unas líneas sobre ti, lo que has construido y el tipo de puesto que buscas.',
    'contact.cancel':                   'Cancelar',
    'contact.send':                     'Enviar',

    // Pricing page
    'pricing.eyebrow':                  'Precio beta',
    'pricing.h.a':                      'Eres de los ',
    'pricing.h.em':                     'primeros',
    'pricing.h.b':                      '. Este precio no vuelve.',
    'pricing.sub':                      'Los usuarios beta que se unan ahora bloquean el precio de fundadores para siempre. Cuando salgamos de beta, sube a 15 €/mes.',
    'pricing.toggle.monthly':           'Mensual',
    'pricing.toggle.annual':            'Anual',
    'pricing.toggle.discount':          '20% de descuento',
    'pricing.tier.basic.tag':           'Para individuos',
    'pricing.tier.basic.name':          'Lingua Basic',
    'pricing.tier.basic.price':         'Gratis',
    'pricing.tier.basic.priceSub':      'para siempre',
    'pricing.tier.basic.lede':          'El comienzo de tu viaje hacia la productividad.',
    'pricing.tier.basic.cta':           'Empezar',
    'pricing.tier.basic.note':          'Empezarás con 30 días de Lingua Pro gratis.',
    'pricing.tier.basic.f.1':           '2.000 palabras / semana en Mac y Windows',
    'pricing.tier.basic.f.2':           '',
    'pricing.tier.basic.f.3':           'Más de 100 idiomas ',
    'pricing.tier.basic.f.4':           'Diccionario y snippets personalizados',
    'pricing.tier.basic.f.5':           '\n',
    'pricing.tier.basic.f.6':           '',
    'pricing.tier.basic.f.7':           '\n',

    'pricing.tier.pro.tag':             'Para individuos y equipos',
    'pricing.tier.pro.name':            'Lingua Pro',
    'pricing.tier.pro.priceMonthly':    '9 €',
    'pricing.tier.pro.priceAnnual':     '10 €',
    'pricing.tier.pro.priceMonthlyOld': '20 €',
    'pricing.tier.pro.priceAnnualOld':  '20 €',
    'pricing.tier.pro.priceUnit':       '/ usuario / mes',
    'pricing.tier.pro.priceUnitAnnual': '/ usuario / mes',
    'pricing.tier.pro.priceSub.monthly':'facturación mensual · precio beta',
    'pricing.tier.pro.priceSub.annual': 'facturación anual · precio beta',
    'pricing.tier.pro.betaBadge':       'Garantizado para siempre — sin subidas futuras',
    'pricing.tier.pro.betaHeadline':    'Precio beta de por vida',
    'pricing.tier.pro.betaStamp':       'DTO.',
    'pricing.tier.pro.lede':            'Todo lo de Basic, además:',
    'pricing.tier.pro.cta':             'Conseguir Lingua Pro',
    'pricing.tier.pro.popular':         'El más popular',
    'pricing.tier.pro.f.1':             'Uso ilimitado',
    'pricing.tier.pro.f.2':             'Traduccion ilimitada',
    'pricing.tier.pro.f.3':             'Diccionario personal ',
    'pricing.tier.pro.f.4':             '',
    'pricing.tier.pro.f.5':             'Acceso anticipado a novedades',

    'pricing.tier.ent.tag':             'Para equipos que necesitan seguridad y soporte avanzados',
    'pricing.tier.ent.name':            'Lingua Enterprise',
    'pricing.tier.ent.price':           'Contáctanos',
    'pricing.tier.ent.priceSub':        'facturación anual',
    'pricing.tier.ent.lede':            'Todo lo de Pro para tu equipo, además:',
    'pricing.tier.ent.cta':             'Hablar con ventas',
    'pricing.tier.ent.f.1':             'Soporte dedicado',
    'pricing.tier.ent.f.2':             'Cumplimiento SOC 2 Type II e ISO 27001',
    'pricing.tier.ent.f.3':             'Features de equipo, dashboards y otros',
    'pricing.tier.ent.f.4':             'Modo privacidad forzado (Zero Data Retention)',
    'pricing.tier.ent.f.5':             '',
    'pricing.tier.ent.f.6':             '',
    'pricing.tier.ent.f.7':             'Descuentos por volumen',
    'pricing.tier.ent.f.8':             'Asientos de admin de TI sin coste adicional',

    'pricing.student.eyebrow':          'Para estudiantes',
    'pricing.student.h':                '3 meses gratis. Luego 50% de descuento para siempre.',
    'pricing.student.b':                'Si eres estudiante, te regalamos los tres primeros meses y después pagas 7,50 €/mes en lugar de 15 €. Si el precio beta está activo (9 €/mes), el precio estudiantil es 4,50 €/mes. Solo necesitas un email universitario.',
    'pricing.student.fine':             'Solo para nuevos suscriptores. Requiere email con dominio universitario (.edu o institucional).',
    'pricing.student.cta':              'Solicitar descuento estudiantil',

    'pricing.compare.h':                'Planes y funciones',
    'pricing.compare.col.basic':        'Basic',
    'pricing.compare.col.pro':          'Pro',
    'pricing.compare.col.ent':          'Enterprise',

    'pricing.compare.sec.devices':      'Dispositivo y plataforma',
    'pricing.compare.row.mac':          'Escritorio (Mac)',
    'pricing.compare.row.win':          'Escritorio (Windows)',
    'pricing.compare.row.ios':          'iPhone',
    'pricing.compare.row.android':      'Android',

    'pricing.compare.sec.typing':       'Dictado por voz sin esfuerzo',
    'pricing.compare.row.dict':         'Diccionario personalizado',
    'pricing.compare.row.words':        'Límite de palabras',
    'pricing.compare.cell.words.basic': '2.000/sem escritorio · 1.000/sem iPhone · Ilimitado Android',
    'pricing.compare.cell.unlimited':   'Ilimitado',
    'pricing.compare.row.langs':        'Más de 100 idiomas',
    'pricing.compare.row.priority':     'Feature requests prioritarios',
    'pricing.compare.row.early':        'Acceso anticipado a novedades',

    'pricing.compare.sec.team':         'Equipo y colaboración',
    'pricing.compare.row.billing':      'Facturación centralizada',
    'pricing.compare.row.shared':       'Diccionario y snippets compartidos',
    'pricing.compare.row.support':      'Soporte al cliente',
    'pricing.compare.cell.support.basic':'Estándar',
    'pricing.compare.cell.support.pro': 'Prioritario',
    'pricing.compare.cell.support.ent': 'Dedicado',
    'pricing.compare.row.dashboards':   'Paneles de uso de equipo',
    'pricing.compare.cell.dash.pro':    'Básico',
    'pricing.compare.cell.dash.ent':    'Avanzado',

    'pricing.compare.sec.security':     'Seguridad y cumplimiento',
    'pricing.compare.row.privacy':      'Modo privacidad (Zero Data Retention)',
    'pricing.compare.cell.enforced':    'Forzado',
    'pricing.compare.row.iso':          'ISO 27001 y SOC 2 Type II',
    'pricing.compare.row.sso':          'SSO / SAML',
    'pricing.compare.row.adminctl':     'Controles de administrador',
    'pricing.compare.row.msa':          'MSA y DPA',
    'pricing.compare.row.hipaa':        'Compatible con HIPAA',

    'pricing.calc.h':                   'Calcula tu ahorro',
    'pricing.calc.hours':               'Paso',
    'pricing.calc.hoursUnit':           'horas tecleando al día',
    'pricing.calc.wordsNote':           'Eso son unas {words} palabras al día.',
    'pricing.calc.rate':                'Mi tiempo vale',
    'pricing.calc.rateUnit':            '/ hora',
    'pricing.calc.savings':             'Al mes, ahorrarás',
    'pricing.calc.row.hoursTyping':     'Horas tecleando',
    'pricing.calc.row.hoursSaved':      'Horas ahorradas al mes',
    'pricing.calc.row.timeValue':       'Valor del tiempo ahorrado',
    'pricing.calc.row.cost':            'Coste mensual de Lingua Pro',

    'pricing.faq.h':                    'Preguntas frecuentes',
    'pricing.faq.q1':                   '¿Cómo paso de Basic a Pro?',
    'pricing.faq.a1':                   'Al registrarte en Lingua obtienes una prueba gratuita de 30 días de Pro. Para hacer upgrade, abre la app y pulsa Probar Lingua Pro. También puedes ir a Plan y facturación dentro de Ajustes.',
    'pricing.faq.q2':                   '¿Hay una prueba gratuita o un plan gratis?',
    'pricing.faq.a2':                   'Sí. Todas las cuentas individuales nuevas incluyen 30 días de prueba de Pro — al terminar pasarás a Lingua Basic (nuestro plan gratis) salvo que hagas upgrade. Cada miembro que invites a un equipo también obtiene su propia prueba de 30 días de Pro.',
    'pricing.faq.q3':                   '¿Puedo cambiar o cancelar mi suscripción en cualquier momento?',
    'pricing.faq.a3':                   'Sí. Puedes gestionar tu suscripción en Plan y facturación en la app de escritorio de Lingua. Si necesitas ayuda, escríbenos desde el portal de soporte.',
    'pricing.faq.q4':                   '¿Ofrecéis descuentos para colectivos específicos?',
    'pricing.faq.a4':                   'Sí — Lingua Pro con descuento para estudiantes, profesores y organizaciones sin ánimo de lucro.',
    'pricing.faq.q5':                   '¿Puedo usar Lingua con todo mi equipo?',
    'pricing.faq.a5':                   'Sí. Lingua Pro funciona para individuos y equipos: sin mínimo de asientos, diccionario y snippets compartidos, facturación centralizada y paneles de uso básicos. Para SSO/SAML, cumplimiento avanzado, paneles y descuentos por volumen, habla con nuestro equipo de Ventas sobre Enterprise.',
  },
};
